# Docker Compose pour Artisania (Frontend + Backend)

services:
  frontend:
    build: ./Front-end
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5001

  backend:
    build: ./Back-end
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/artisania
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - mongo
    volumes:
      - ./Back-end/src/uploads:/app/src/uploads

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
